stages:
    - release

release:
    stage: release
    image: registry.gitlab.com/gitlab-org/release-cli
    when: manual
    except:
        - tags
    script:
        - release-cli create --name "v1.0.0" --description "New release using the release-cli $EXTRA_DESCRIPTION" --tag-name "v1.0.0" --ref $CI_COMMIT_SHA