image: maven:latest

before_script: []
stages:
  - build
  - test
  - release

documentation:
  image: "timnn/texlive"
  stage: "build"
  script: [
      "apt-get update && apt-get install -y python3-pip",
      "pip3 install Pygments",
      "cd documentation",
      "pdflatex -synctex=1 --shell-escape -interaction=nonstopmode Main.tex",
      "bibtex Main",
      "pdflatex -synctex=1 --shell-escape -interaction=nonstopmode Main.tex",
      "pdflatex -synctex=1 --shell-escape -interaction=nonstopmode Main.tex"
      ]
  artifacts:
    paths:
      - documentation/Main.pdf

build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Building extension"
    - mvn -B clean compile -U
    - mvn -B assembly:single
  artifacts:
    paths:
      - target/*.{zip,tgz}
    expire_in: never

test:
  stage: test
  script:
    - mvn -B clean test

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo 'running release job'
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: './changelog/$CI_COMMIT_TAG.md'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: 'osm-extractor-$CI_COMMIT_TAG.zip'
          url: 'https://gitlab.com/labiangashi/osm-extractor/-/jobs/artifacts/$CI_COMMIT_TAG/raw/target/osm-extractor-$CI_COMMIT_TAG.zip?job=build'
        - name: 'osm-extractor-$CI_COMMIT_TAG.tgz'
          url: 'https://gitlab.com/labiangashi/osm-extractor/-/jobs/artifacts/$CI_COMMIT_TAG/raw/target/osm-extractor-$CI_COMMIT_TAG.tgz?job=build'
        - name: 'Documentation.pdf'
          url: 'https://gitlab.com/labiangashi/osm-extractor/-/jobs/artifacts/$CI_COMMIT_TAG/raw/documentation/Main.pdf?job=documentation'


